### ISSUE TITLE
Responsive design testing 

### ISSUE THREAD

**Issue by zannain** [CarlosSengo/tea-cozy#1]
Make sure to do responsive-testing of a webpage by viewing it in various browsers and sizes. Browsers have their own unique quirks and becoming familiar with them will prove beneficial because responsive design is becoming so important in web development today. As a developer, you don't control what browser a client or user is using so its best to be prepared for all of them. Notice your webpage began to break down as I resized it.

![image](https://user-images.githubusercontent.com/24375741/39677718-b2469106-514d-11e8-9226-433f37afe508.png)

Mastering developer tools will help you figure out the page size at which things on your page are going awry and then the next step is to create media queries that will correct the UI defect. Media queries are CSS styles that only execute when the browser window is a certain size. To learn more about responsive design I highly recommend checking out [Codecademy's course](https://www.codecademy.com/learn/learn-responsive-design) on it.

**Comment by CarlosSengo** [comment]
Indeed, to be honest with you I was focusing on site layout as this was a Flexbox assignment. I'm now going through Unit 5 of Build websites from scratch where I'm starting to get a better grasp of responsive design. I will incorporate it in my development flow. Thanks for great advise, Cheers
